// <auto-generated />
using System;
using GestionStock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionStock.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260522211220_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("GestionStock.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "PC portables et desktops",
                            Nom = "Ordinateurs"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Souris, claviers, écrans...",
                            Nom = "Périphériques"
                        },
                        new
                        {
                            Id = 3,
                            Description = "RAM, disques durs, processeurs...",
                            Nom = "Composants"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Routeurs, switches, câbles...",
                            Nom = "Réseaux"
                        });
                });

            modelBuilder.Entity("GestionStock.Models.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motif")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("MouvementsStock");
                });

            modelBuilder.Entity("GestionStock.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantiteEnStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeuilAlerte")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            CategorieId = 1,
                            DateAjout = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intel Core i5, 8GB RAM, 256GB SSD",
                            Nom = "Laptop Dell Inspiron 15",
                            PrixUnitaire = 650000m,
                            QuantiteEnStock = 10,
                            Reference = "PC-001",
                            SeuilAlerte = 3
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            CategorieId = 2,
                            DateAjout = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Souris filaire USB",
                            Nom = "Souris Logitech M100",
                            PrixUnitaire = 8000m,
                            QuantiteEnStock = 50,
                            Reference = "PER-001",
                            SeuilAlerte = 10
                        },
                        new
                        {
                            Id = 3,
                            Actif = true,
                            CategorieId = 3,
                            DateAjout = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mémoire DDR4 2666MHz",
                            Nom = "RAM Kingston 8GB DDR4",
                            PrixUnitaire = 25000m,
                            QuantiteEnStock = 30,
                            Reference = "COM-001",
                            SeuilAlerte = 5
                        });
                });

            modelBuilder.Entity("GestionStock.Models.MouvementStock", b =>
                {
                    b.HasOne("GestionStock.Models.Produit", "Produit")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("GestionStock.Models.Produit", b =>
                {
                    b.HasOne("GestionStock.Models.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("GestionStock.Models.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("GestionStock.Models.Produit", b =>
                {
                    b.Navigation("MouvementsStock");
                });
#pragma warning restore 612, 618
        }
    }
}
